#!/usr/bin/env bash
#Automatic Script to install CloudFlared and perform basic settings 
cd /tmp
mkdir bruto_temp
cd /tmp/bruto_temp/
#Download Cloudflared for Pi
wget https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-arm.tgz
#extract
tar -xvzf cloudflared-stable-linux-arm.tgz

#move binary to the right place
sudo cp ./cloudflared /usr/local/bin
sudo chmod +x /usr/local/bin/cloudflared
# command to check version / issues "cloudflared -v"

#add cloudflared user
sudo useradd -s /usr/sbin/nologin -r -M cloudflared
# add the config
sudo echo "CLOUDFLARED_OPTS=--port 5053 --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query" > /etc/default/cloudflared
#fix permissions
sudo chown cloudflared:cloudflared /etc/default/cloudflared
sudo chown cloudflared:cloudflared /usr/local/bin/cloudflared