#!/usr/bin/env bash
#Automatic Script to install CloudFlared and perform basic settings 
cd /tmp
mkdir bruto_temp
cd /tmp/bruto_temp/
#Download Cloudflared for Pi
echo "Downloading the lastes Cloudflared binary"
wget "https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-arm.tgz"
#extract
echo "Extracting the binary and moving to the right place"
tar -xvzf cloudflared-stable-linux-arm.tgz

#move binary to the right place
cp ./cloudflared /usr/local/bin
chmod +x /usr/local/bin/cloudflared
# command to check version / issues "cloudflared -v"

#add cloudflared user
echo "Adding the cloudflared user and initial config"
useradd -s /usr/sbin/nologin -r -M cloudflared
# add the config
echo "CLOUDFLARED_OPTS=--port 5053 --upstream https://1.1.1.1/dns-query --upstream https://1.0.0.1/dns-query" > /etc/default/cloudflared
#fix permissions
chown cloudflared:cloudflared /etc/default/cloudflared
chown cloudflared:cloudflared /usr/local/bin/cloudflared
echo "Installing the CloudFlared Service"
#get config
wget "https://raw.githubusercontent.com/hprax/pihole-bruto/master/install/cloudflared.service"
cp ./cloudflared.service /etc/systemd/system/

#creating service and enabling it
#systemctl enable cloudflared
#systemctl start cloudflared
#systemctl status cloudflared